[package]

name = "promise"
version = "0.0.4"
authors = ["Kevin Walter <kevin.walter.private@googlemail.com>"]
repository = "https://github.com/lucidd/rust-promise"
description = """
A simple future/promise library for rust
"""
license = "MIT"

[lib]

name = "promise"
